<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DesktopNeedsWorkResult</name>
   <tag></tag>
   <elementGuidId>b0e1d344-796f-49be-9e71-fe9a00aae2b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='page-speed-insights']/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/p[2]</value>
   </webElementProperties>
</WebElementEntity>
